### Get all users in DB
GET http://localhost:3001/users

### Get a user by ID
GET http://localhost:3001/users/{id}

### Create a new user
POST http://localhost:3001/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "password123",
  "nickname": "Johnny",
  "age": 30
}

### Update a user by ID
PUT http://localhost:3001/users/68884edb4a1f21a4eb545411
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "password123456",
  "nickname": "Johnny",
  "age": 31
}

### Delete a user by ID
DELETE http://localhost:3001/users/{id}


//=======================TASKS SECTION=======================//

### Get all tasks in DB
GET http://localhost:3001/users/68884edb4a1f21a4eb545411/tasks

### Get a task by ID
GET http://localhost:3001/users/68884edb4a1f21a4eb545411/tasks/688a6349ed9ff331447bb41a


### Create a new task
POST http://localhost:3001/users/68884edb4a1f21a4eb545411/tasks
Content-Type: application/json

{
  "title": "New Task2",
  "description": "Task description",
  "status": "pending",
  "dueDate": "2023-12-31",
  "priority": "medium"
}

### Update a task by ID
PUT http://localhost:3001/tasks/{id}
Content-Type: application/json

{
  "title": "Updated Task",
  "description": "Updated description",
  "status": "in-progress",
  "dueDate": "2024-01-31",
  "priority": "high"
}

### Delete a task by ID
DELETE http://localhost:3001/tasks/{id}

//==============================================//
              # PRODUCTION SECTION
//==============================================//

### Get All tasks by USER ID
GET https://project2-api-rest.onrender.com/users/68884edb4a1f21a4eb545411/tasks

### Creating a new task by USER ID
POST https://project2-api-rest.onrender.com/users/68884edb4a1f21a4eb545411/tasks
Content-Type: application/json

{
  "title": "New Task1",
  "description": "Task description",
  "status": "pending",
  "dueDate": "2023-12-31",
  "priority": "medium"
}

### Updating a task by USER ID
PUT https://project2-api-rest.onrender.com/users/68884edb4a1f21a4eb545411/tasks/688a78d9d817526e1e42ae6d
Content-Type: application/json

{
  "title": "Updated Task",
  "description": "Updated description",
  "status": "completedaaaaadoooo",
  "dueDate": "2024-01-31",
  "priority": "high"
}